version: "3"

services:
  vcs-backend:
    tty: true
    container_name: vcs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      vcs-db:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DB_HOST: vcs-db
      DB_NAME: vcs
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: password
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  vcs-db:
    image: postgres
    container_name: vcs-db
    environment:
      PGPORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: vcs
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres -d vcs
      interval: 1s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vcs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Your frontend Dockerfile
    container_name: vcs-frontend
    ports:
      - "3000:3000" # Adjust the port to suit your frontend app's port
    depends_on:
      - vcs-backend
    restart: always
    volumes:
      - ./build:/var/task/.next/rw

  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:r # if modifications are needed at runtime
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./build:/app/.next/:ro
    depends_on:
      - vcs-frontend

  certbot:
    depends_on:
      - nginx-server
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

    #normal run
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    #initial cert
    #command: certonly --webroot --webroot-path=/var/www/certbot --email william.redgard@gmail.com --agree-tos --no-eff-email --domains lfv.popify.se

    #expand
    #command: certonly --expand --webroot --webroot-path=/var/www/certbot --email william.redgard@gmail.com --agree-tos --no-eff-email --domains lfv.popify.se
