version: "3"

services:
  vcs-backend:
    tty: true
    container_name: vcs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: prod
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  vcs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Your frontend Dockerfile
    container_name: vcs-frontend
    ports:
      - "3000:3000" # Adjust the port to suit your frontend app's port
    depends_on:
      - vcs-backend
    restart: always
    volumes:
      - ./build:/var/task/.next/rw

  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:r # if modifications are needed at runtime
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./build:/app/.next/:ro
    depends_on:
      - vcs-frontend

  certbot:
    depends_on:
      - nginx-server
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

    #normal run
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
