FROM node:18.17.0-alpine
RUN mkdir -p /var/task
WORKDIR /var/task
COPY package*.json /var/task/
COPY src /var/task/src
COPY tsconfig.json /var/task/
RUN npm install
EXPOSE 8080

CMD ["npm", "run", "start"]

