version: "3"

services:
  vcs-backend:
    tty: true
    container_name: vcs-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      vcs-db:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      DB_HOST: vcs-db
      DB_NAME: vcs
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: password
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

    command: sh -c "npm run start"
    volumes:
      - ./:/var/task

  vcs-db:
    image: postgres
    container_name: vcs-db
    environment:
      PGPORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: vcs
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres -d vcs
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
